language: php

php:
- '5.6'
- '7'

before_script:
  - composer self-update
  - composer install --dev

script:
  - ./vendor/bin/phpcs --standard=psr2 -n --ignore=vendor --extensions=php .
  - ./vendor/bin/phpunit
  - ./vendor/bin/test-reporter
