version: "2"
services:
  app: &main
    image: keboola/google-analytics-extractor
    build:
      context: .
    environment:
      - CLIENT_ID
      - CLIENT_SECRET
      - ACCESS_TOKEN
      - REFRESH_TOKEN
      - VIEW_ID

  dev:
    <<: *main
    volumes:
      - ./:/code
      - ./data:/data
    mem_limit: 4000m
    mem_reservation: 4000m
