version: "2"
services:
  app: &main
    image: keboola/google-analytics-extractor
    build:
      context: .
    environment:
      CLIENT_ID: $CLIENT_ID
      CLIENT_SECRET: $CLIENT_SECRET
      ACCESS_TOKEN: $ACCESS_TOKEN
      REFRESH_TOKEN: $REFRESH_TOKEN
      VIEW_ID: $VIEW_ID

  dev:
    <<: *main
    volumes:
      - ./:/code
      - ./data:/data
    mem_limit: 4000m
    mem_reservation: 4000m
