services:
  app: &main
    image: keboola/google-analytics-extractor
    build:
      context: .
    environment:
      - KBC_DATA_TYPE_SUPPORT=none
      - CLIENT_ID
      - CLIENT_SECRET
      - ACCESS_TOKEN
      - REFRESH_TOKEN
      - SERVICE_ACCOUNT_JSON
      - VIEW_ID
      - KBC_URL
      - KBC_TOKEN
      - KBC_CONFIGID
      - KBC_COMPONENTID

  dev:
    <<: *main
    volumes:
      - ./:/code
      - ./data:/data
    mem_limit: 4000m
    mem_reservation: 4000m
